## Plotting the evolution of the Emission of PM-25 generated by "motor
## vehicles" during the years 1999 through 2008 over Beltimore compared to Los Angeles 
## We assume this corresponds to the variable type = ON-ROAD 

## We assume we are in the correct directory 
## Importing data : (only what is necessary here, NEI) : 
NEI <- readRDS("summarySCC_PM25.rds")

## library : 
library(ggplot2)

## Generating Data : 
Index <- (NEI$fips == "24510" | NEI$fips == "06037")
Data <- NEI[Index, ]
Index <- (Data$type == "ON-ROAD")
Data <- Data[Index, ]

#ploting : 
qplot(year, Emissions, data = Data, facets = ~fips, 
      xlab = "Year", ylab = "Emission de PM-25 (tons)", 
      main = "Evolution of Pollution through Time in LA and Baltimore",  
      geom = c("point", "smooth"), method = "glm", 
      size = I(2), color = fips, ylim = c(0, 5), na.rm = TRUE)


#Selecting Plotting device : 
png(file = "Plot 6.png")


#Turning Device off : 
dev.off()

