## Plotting the evolution of the Emission of PM-25 generated by "motor
## vehicles" during the years 1999 through 2008 over Beltimore
## We assume this corresponds to the variable type = ON-ROAD 

## We assume we are in the correct directory 
## Importing data : (only what is necessary here, NEI) : 
NEI <- readRDS("summarySCC_PM25.rds")

## library : 
library(ggplot2)

## Generating Data : 
Index <- (NEI$fips == 24510 & NEI$type == "ON-ROAD")
Data <- NEI[Index, ]

#Selecting Plotting device : 
png(file = "Plot 5.png")

qplot(year, Emissions, data = Data, geom = c("point", "smooth"), 
      xlab = "Year", ylab = "Emission of PM-25 (tons)", 
      main = "Evolution of Pollution through time by motor vehicle over Baltimore ",  
      method = "glm", size = I(2), ylim = c(0, 10))

#Turning Device off : 
dev.off()
